https://geo2.hyphae.design/datasets/geonode:power_plants_nationwide/dataset_download
https://geo2.hyphae.design/datasets/geonode:conus_lcz_warp_t_4326_1192f59ac9496d0764a8177cac31779a/dataset_download
https://geo2.hyphae.design/datasets/geonode:private_schools_nationwide_4326/dataset_download 
https://geo2.hyphae.design/datasets/geonode:na_cec_eco_level1/dataset_download 
https://geo2.hyphae.design/datasets/geonode:na_cec_eco_level2/dataset_download 
https://geo2.hyphae.design/datasets/geonode:na_cec_eco_level3/dataset_download
https://geo2.hyphae.design/datasets/geonode:us_eco_l4_state_boundaries_20231013t210637z_001/dataset_download
https://geo2.hyphae.design/datasets/geonode:nursing_homes/embed
https://geo2.hyphae.design/datasets/geonode:public_school_locations_2018_19/dataset_download
https://geo2.hyphae.design/datasets/geonode:koppen_geiger_fixed/embed